# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  environment: Dev


steps:
          - task: SonarQubePrepare@5
            inputs:
                SonarQube: 'Sonarqube'
                scannerMode: 'MSBuild'
                projectKey: 'niks-scot_niks-scot_AYvIa7pKaFL0an70kLdD'
                projectName: 'Niks_scot'
                
          - task: SonarQubeAnalyze@5
            inputs:
              jdkversion: 'JAVA_HOME_11_X64'

          - task: SonarQubePublish@5
            inputs:
              pollingTimeoutSec: '300'
                

