# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  environment: Dev

steps:
     - task: NodeTool@0
       inputs:
        versionSpec: '12.x'
       displayName: 'Install Node.js'

     - script: |
          npm install
          npm run build
       displayName: 'Install and Build'

     - script: echo Hello, world!
       displayName: 'Run a one-line script'

     - script: echo Add other tasks to build, test, and deploy your project.
       displayName: 'Run a multi-line script'
       
     - task: SonarQubePrepare@5
       inputs:
        SonarQube: 'Sonarqube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'sonarproject'
        cliProjectName: 'TetrisSonar'
        cliSources: '.'
        extraProperties: |
          # Additional properties that will be passed to the scanner, 
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.java.binaries=.
          sonar.branch.name=main

     - task: SonarQubeAnalyze@5
       inputs:
          jdkversion: 'JAVA_HOME_11_X64'

     - task: SonarQubePublish@5
       inputs:
        pollingTimeoutSec: '300'